#!/bin/bash

set -o errexit
set -o pipefail

# Let the DB start
python -m a8t_tools.db.wait_for_db

alembic upgrade head

# Create superuser
if [ -n "${ADMIN_EMAIL}" ]; then
  python manage.py create-superuser "${ADMIN_USERNAME}" "${ADMIN_EMAIL}" "${ADMIN_PASSWORD}" || true
fi

# Create survey table
for CATEGORY in "${CATEGORY1}" "${CATEGORY2}" "${CATEGORY3}" "${CATEGORY4}" "${CATEGORY5}" "${CATEGORY6}" "${CATEGORY7}" "${CATEGORY8}" "${CATEGORY9}" "${CATEGORY10}"; do
  if [ -n "${CATEGORY}" ]; then
    python manage.py create-survey "${CATEGORY}" || true
  fi
done

# Create question table
TITLES=("$TITLE1" "$TITLE2" "$TITLE3" "$TITLE4" "$TITLE5" "$TITLE6" "$TITLE7" "$TITLE8" "$TITLE9" "$TITLE10" "$TITLE11" "$TITLE12" "$TITLE13" "$TITLE14" "$TITLE15" "$TITLE16" "$TITLE17" "$TITLE18" "$TITLE19" "$TITLE20" "$TITLE21" "$TITLE22" "$TITLE23" "$TITLE24" "$TITLE25" "$TITLE26" "$TITLE27" "$TITLE28" "$TITLE29" "$TITLE30" "$TITLE31")
SURVEY_IDS=("$SURVEY_ID1" "$SURVEY_ID2" "$SURVEY_ID3" "$SURVEY_ID4" "$SURVEY_ID5" "$SURVEY_ID6" "$SURVEY_ID7" "$SURVEY_ID8" "$SURVEY_ID9" "$SURVEY_ID10" "$SURVEY_ID11" "$SURVEY_ID12" "$SURVEY_ID13" "$SURVEY_ID14" "$SURVEY_ID15" "$SURVEY_ID16" "$SURVEY_ID17" "$SURVEY_ID18" "$SURVEY_ID19" "$SURVEY_ID20" "$SURVEY_ID21" "$SURVEY_ID22" "$SURVEY_ID23" "$SURVEY_ID24" "$SURVEY_ID25" "$SURVEY_ID26" "$SURVEY_ID27" "$SURVEY_ID28" "$SURVEY_ID29" "$SURVEY_ID30" "$SURVEY_ID31")
DESCRIPTIONS=("$DESCRIPTION1" "$DESCRIPTION2" "$DESCRIPTION3" "$DESCRIPTION4" "$DESCRIPTION5" "$DESCRIPTION6" "$DESCRIPTION7" "$DESCRIPTION8" "$DESCRIPTION9" "$DESCRIPTION10" "$DESCRIPTION11" "$DESCRIPTION12" "$DESCRIPTION13" "$DESCRIPTION14" "$DESCRIPTION15" "$DESCRIPTION16" "$DESCRIPTION17" "$DESCRIPTION18" "$DESCRIPTION19" "$DESCRIPTION20" "$DESCRIPTION21" "$DESCRIPTION22" "$DESCRIPTION23" "$DESCRIPTION24" "$DESCRIPTION25" "$DESCRIPTION26" "$DESCRIPTION27" "$DESCRIPTION28" "$DESCRIPTION29" "$DESCRIPTION30" "$DESCRIPTION31")
SHORT_DESCRIPTIONS=("$SHORT_DESCRIPTION1" "$SHORT_DESCRIPTION2" "$SHORT_DESCRIPTION3" "$SHORT_DESCRIPTION4" "$SHORT_DESCRIPTION5" "$SHORT_DESCRIPTION6" "$SHORT_DESCRIPTION7" "$SHORT_DESCRIPTION8" "$SHORT_DESCRIPTION9" "$SHORT_DESCRIPTION10" "$SHORT_DESCRIPTION11" "$SHORT_DESCRIPTION12" "$SHORT_DESCRIPTION13" "$SHORT_DESCRIPTION14" "$SHORT_DESCRIPTION15" "$SHORT_DESCRIPTION16" "$SHORT_DESCRIPTION17" "$SHORT_DESCRIPTION18" "$SHORT_DESCRIPTION19" "$SHORT_DESCRIPTION20" "$SHORT_DESCRIPTION21" "$SHORT_DESCRIPTION22" "$SHORT_DESCRIPTION23" "$SHORT_DESCRIPTION24" "$SHORT_DESCRIPTION25" "$SHORT_DESCRIPTION26" "$SHORT_DESCRIPTION27" "$SHORT_DESCRIPTION28" "$SHORT_DESCRIPTION29" "$SHORT_DESCRIPTION30" "$SHORT_DESCRIPTION31")
POINTS=("$POINTS1" "$POINTS2" "$POINTS3" "$POINTS4" "$POINTS5" "$POINTS6" "$POINTS7" "$POINTS8" "$POINTS9" "$POINTS10" "$POINTS11" "$POINTS12" "$POINTS13" "$POINTS14" "$POINTS15" "$POINTS16" "$POINTS17" "$POINTS18" "$POINTS19" "$POINTS20" "$POINTS21" "$POINTS22" "$POINTS23" "$POINTS24" "$POINTS25" "$POINTS26" "$POINTS27" "$POINTS28" "$POINTS29" "$POINTS30" "$POINTS31")
DISTANCES=("$DISTANCE1" "$DISTANCE2" "$DISTANCE3" "$DISTANCE4" "$DISTANCE5" "$DISTANCE6" "$DISTANCE7" "$DISTANCE8" "$DISTANCE9" "$DISTANCE10" "$DISTANCE11" "$DISTANCE12" "$DISTANCE13" "$DISTANCE14" "$DISTANCE15" "$DISTANCE16" "$DISTANCE17" "$DISTANCE18" "$DISTANCE19" "$DISTANCE20" "$DISTANCE21" "$DISTANCE22" "$DISTANCE23" "$DISTANCE24" "$DISTANCE25" "$DISTANCE26" "$DISTANCE27" "$DISTANCE28" "$DISTANCE29" "$DISTANCE30" "$DISTANCE31")
TIMES=("$TIME1" "$TIME2" "$TIME3" "$TIME4" "$TIME5" "$TIME6" "$TIME7" "$TIME8" "$TIME9" "$TIME10" "$TIME11" "$TIME12" "$TIME13" "$TIME14" "$TIME15" "$TIME16" "$TIME17" "$TIME18" "$TIME19" "$TIME20" "$TIME21" "$TIME22" "$TIME23" "$TIME24" "$TIME25" "$TIME26" "$TIME27" "$TIME28" "$TIME29" "$TIME30" "$TIME31")
PRICES=("$PRICE1" "$PRICE2" "$PRICE3" "$PRICE4" "$PRICE5" "$PRICE6" "$PRICE7" "$PRICE8" "$PRICE9" "$PRICE10" "$PRICE11" "$PRICE12" "$PRICE13" "$PRICE14" "$PRICE15" "$PRICE16" "$PRICE17" "$PRICE18" "$PRICE19" "$PRICE20" "$PRICE21" "$PRICE22" "$PRICE23" "$PRICE24" "$PRICE25" "$PRICE26" "$PRICE27" "$PRICE28" "$PRICE29" "$PRICE30" "$PRICE31")
IMAGE_PATHS=("$IMAGE_PATH1" "$IMAGE_PATH2" "$IMAGE_PATH3" "$IMAGE_PATH4" "$IMAGE_PATH5" "$IMAGE_PATH6" "$IMAGE_PATH7" "$IMAGE_PATH8" "$IMAGE_PATH9" "$IMAGE_PATH10" "$IMAGE_PATH11" "$IMAGE_PATH12" "$IMAGE_PATH13" "$IMAGE_PATH14" "$IMAGE_PATH15" "$IMAGE_PATH16" "$IMAGE_PATH17" "$IMAGE_PATH18" "$IMAGE_PATH19" "$IMAGE_PATH20" "$IMAGE_PATH21" "$IMAGE_PATH22" "$IMAGE_PATH23" "$IMAGE_PATH24" "$IMAGE_PATH25" "$IMAGE_PATH26" "$IMAGE_PATH27" "$IMAGE_PATH28" "$IMAGE_PATH29" "$IMAGE_PATH30" "$IMAGE_PATH31")

for ((i=0; i<${#TITLES[@]}; i++)); do
  TITLE="${TITLES[i]}"
  SURVEY_ID="${SURVEY_IDS[i]}"
  DESCRIPTION="${DESCRIPTIONS[i]}"
  SHORT_DESCRIPTION="${SHORT_DESCRIPTIONS[i]}"
  POINTS="${POINTS[i]}"
  DISTANCE="${DISTANCES[i]}"
  TIME="${TIMES[i]}"
  PRICE="${PRICES[i]}"
  IMAGE_PATH="${IMAGE_PATHS[i]}"

  if [ -n "${TITLE}" ]; then
    python manage.py create-question "${TITLE}" "${SURVEY_ID}" "${DESCRIPTION}" "${SHORT_DESCRIPTION}" "${POINTS}" "${DISTANCE}" "${TIME}" "${PRICE}" "${IMAGE_PATH}" || true
  fi
done


exec "$@"